### ISSUE TITLE
Docs: 커밋메시지, 이슈, PR 템플릿 적용

### ISSUE THREAD

**Issue by kim-yehyeon** [yeaaaaahhhhh/myBlog#1]
- [x] 커밋 메시지 템플릿 적용
- [x] GitHub 이슈 템플릿 적용
- [x] GitHub PR 템플릿 적용

**Comment by cheesecat47** [comment]
75ac341 커밋 메시지에 명령어 포함한거지? 나 같은 경우에는 커밋 메시지는 마크다운이 아니긴 한데 저기도 그냥 마크다운처럼 `brew install` 이렇게 적긴 해 ㅋㅋ

**Comment by kim-yehyeon** [comment]
> [75ac341](https://github.com/yeaaaaahhhhh/myBlog/commit/75ac341f7177779d477996aebe389eb267471324) 커밋 메시지에 명령어 포함한거지? 나 같은 경우에는 커밋 메시지는 마크다운이 아니긴 한데 저기도 그냥 마크다운처럼 `brew install` 이렇게 적긴 해 ㅋㅋ

응! 혹시 누군가 보고 탐날까봐…ㅎㅎㅎ 같이 쓰자는 의미에서 추가해보았습니당
근데 이제보니까 이슈 하나 당 pr 하나네 ㅎㅎ;;; 수정해야하겠다
